// <auto-generated />
namespace PRS_web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedgetaddchangeremovetoPurchaserequestlineitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgetaddchangeremovetoPurchaserequestlineitems));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041530257_added get add change remove to Purchase request line items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
