// <auto-generated />
namespace PRS_web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmigrationconfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmigrationconfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021903452_added migration config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
